const FETCH_USER = 'FETCH_USER';
const FETCH_GAMES = 'FETCH_GAMES';
const CREATE_GAME = 'CREATE_GAME';
const UPDATE_GAME = 'UPDATE_GAME';
const FETCH_QUESTIONS = 'FETCH_QUESTIONS';

module.exports = {
  FETCH_USER,
  FETCH_GAMES,
  CREATE_GAME,
  UPDATE_GAME,
  FETCH_QUESTIONS
};
