const SET_GAME_SOCKET = 'SET_GAME_SOCKET';
const GET_GAME_QUESTIONS = 'GET_GAME_QUESTIONS';
const UPDATE_QUESTION = 'UPDATE_QUESTION';
const FETCH_TEST_CASES = 'FETCH_TEST_CASES';
const SET_TEST_RESULTS = 'SET_TEST_RESULTS';
const FETCH_TEST_RESULTS = 'FETCH_TEST_RESULTS';
const FETCH_PLAYER = 'FETCH_PLAYER';
const FETCH_USER = 'FETCH_USER';
const FETCH_GAMES = 'FETCH_GAMES';
const CREATE_GAME = 'CREATE_GAME';
const UPDATE_GAME = 'UPDATE_GAME';
const GET_SCORE = 'GET_SCORE';
const UPDATE_SCORE = 'UPDATE_SCORE';

module.exports = {
  SET_GAME_SOCKET,
  GET_GAME_QUESTIONS,
  UPDATE_QUESTION,
  FETCH_TEST_CASES,
  SET_TEST_RESULTS,
  FETCH_TEST_RESULTS,
  FETCH_PLAYER,
  FETCH_USER,
  FETCH_GAMES,
  CREATE_GAME,
  UPDATE_GAME,
  GET_SCORE,
  UPDATE_SCORE
};
