/* eslint-disable import/prefer-default-export */
const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS';
const FETCH_TEST_CASES = 'FETCH_TEST_CASES';
const FETCH_TEST_RESULTS = 'FETCH_TEST_RESULTS';
const FETCH_USER = 'FETCH_USER';
const FETCH_GAMES = 'FETCH_GAMES';
const CREATE_GAME = 'CREATE_GAME';

module.exports = {
  GET_ALL_QUESTIONS,
  FETCH_TEST_CASES,
  FETCH_TEST_RESULTS,
  FETCH_USER,
  FETCH_GAMES,
  CREATE_GAME
};
